// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PowerMessenger.Infrastructure.Persistence.Context;

#nullable disable

namespace PowerMessenger.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MessengerEfContext))]
    [Migration("20230620160704_PersistenceMigration")]
    partial class PersistenceMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PowerMessenger.Domain.Entities.Chat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_type_id");

                    b.Property<DateTimeOffset>("DateCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_create");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Photo")
                        .HasColumnType("text")
                        .HasColumnName("photo");

                    b.HasKey("Id")
                        .HasName("pk_chats");

                    b.HasIndex("ChatTypeId")
                        .HasDatabaseName("ix_chats_chat_type_id");

                    b.ToTable("chats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ChatTypeId = 2L,
                            DateCreate = new DateTimeOffset(new DateTime(2023, 6, 20, 16, 7, 4, 359, DateTimeKind.Unspecified).AddTicks(3441), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Чат для .NET разработчиков и C# программистов.",
                            Name = "Group1",
                            Photo = "ChatsImage/efe4e2f6-d7b2-49f4-80bf-a2b5e8fa7178.jpg"
                        },
                        new
                        {
                            Id = 2L,
                            ChatTypeId = 2L,
                            DateCreate = new DateTimeOffset(new DateTime(2023, 6, 20, 16, 7, 4, 359, DateTimeKind.Unspecified).AddTicks(3445), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Стараемся не флудить. Пишем по делу. Правила: https://t.me/professorweb/430450 Для флуда @svoboda_obsh",
                            Name = "DOT.NET Talking",
                            Photo = "ChatsImage/5009efc6-6891-44b6-8d20-68ec9a9199de.jpg"
                        });
                });

            modelBuilder.Entity("PowerMessenger.Domain.Entities.ChatParticipant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_participants");

                    b.HasIndex("ChatId")
                        .HasDatabaseName("ix_chat_participants_chat_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_chat_participants_user_id");

                    b.ToTable("chat_participants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ChatId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            ChatId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            ChatId = 2L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            ChatId = 2L,
                            UserId = 2L
                        });
                });

            modelBuilder.Entity("PowerMessenger.Domain.Entities.ChatType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_chat_types");

                    b.ToTable("chat_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Type = "Personal"
                        },
                        new
                        {
                            Id = 2L,
                            Type = "Group"
                        });
                });

            modelBuilder.Entity("PowerMessenger.Domain.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("DateCreate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_create");

                    b.Property<bool>("DeletedByAll")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted_by_all");

                    b.Property<long?>("DeletedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<long?>("ForwardedMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("forwarded_message_id");

                    b.Property<long>("MessageTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_type_id");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ChatId")
                        .HasDatabaseName("ix_messages_chat_id");

                    b.HasIndex("DeletedByUserId")
                        .HasDatabaseName("ix_messages_deleted_by_user_id");

                    b.HasIndex("ForwardedMessageId")
                        .HasDatabaseName("ix_messages_forwarded_message_id");

                    b.HasIndex("MessageTypeId")
                        .HasDatabaseName("ix_messages_message_type_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_messages_user_id");

                    b.ToTable("messages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ChatId = 1L,
                            Content = "Привет",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            ChatId = 1L,
                            Content = "Дарова",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 31, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            ChatId = 1L,
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 32, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            ChatId = 1L,
                            Content = "Нормально",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 33, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            ChatId = 1L,
                            Content = "HelloWorld",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 34, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            ChatId = 1L,
                            Content = "Если бы не характер, то природная смекалка, хитрость и отвага, доходящая до авантюризма,\r\nсделали бы его в наше время очень богатым",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 35, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 7L,
                            ChatId = 1L,
                            Content = "Eiusmod id pariatur reprehenderit minim ea est laboris. \r\nDo consectetur officia consectetur consequat deserunt. In labore excepteur non ipsum esse commodo officia. \r\nAliquip sit aliquip laborum dolor nisi mollit consequat exercitation sit laboris in reprehenderit exercitation.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 36, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            ChatId = 1L,
                            Content = "Eiusmod id pariatur reprehenderit minim ea est laboris. \r\nDo consectetur officia consectetur consequat deserunt. In labore excepteur non ipsum esse commodo officia. \r\nAliquip sit aliquip laborum dolor nisi mollit consequat exercitation sit laboris in reprehenderit exercitation.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 37, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 9L,
                            ChatId = 1L,
                            Content = "Eiusmod id pariatur reprehenderit minim ea est laboris. \r\nDo consectetur officia consectetur consequat deserunt. In labore excepteur non ipsum esse commodo officia. \r\nAliquip sit aliquip laborum dolor nisi mollit consequat exercitation sit laboris in reprehenderit exercitation.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 38, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            ChatId = 1L,
                            Content = "Eiusmod id pariatur reprehenderit minim ea est laboris. \r\nDo consectetur officia consectetur consequat deserunt. In labore excepteur non ipsum esse commodo officia. \r\nAliquip sit aliquip laborum dolor nisi mollit consequat exercitation sit laboris in reprehenderit exercitation.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 39, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 11L,
                            ChatId = 1L,
                            Content = "Cupidatat exercitation et culpa nisi consectetur laborum eu voluptate enim deserunt nostrud.\r\nVoluptate id nulla exercitation enim do qui elit proident ullamco qui pariatur cillum. \r\nPariatur ea eu duis laborum occaecat deserunt.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 40, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 12L,
                            ChatId = 1L,
                            Content = "Eiusmod dolore est id ipsum mollit ex.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 41, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 13L,
                            ChatId = 1L,
                            Content = "Dolore enim ea est incididunt do",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 42, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 14L,
                            ChatId = 2L,
                            Content = "Eiusmod dolore est id ipsum mollit ex.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 43, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 15L,
                            ChatId = 2L,
                            Content = "Cupidatat exercitation et culpa nisi consectetur laborum eu voluptate enim deserunt nostrud.\r\nVoluptate id nulla exercitation enim do qui elit proident ullamco qui pariatur cillum. \r\nPariatur ea eu duis laborum occaecat deserunt.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 44, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 16L,
                            ChatId = 2L,
                            Content = "Eiusmod dolore est id ipsum mollit ex.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 17L,
                            ChatId = 2L,
                            Content = "Dolore enim ea est incididunt do",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 46, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 18L,
                            ChatId = 2L,
                            Content = "Привет!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 46, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 19L,
                            ChatId = 2L,
                            Content = "Как дела?",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 46, 2, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 18L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 20L,
                            ChatId = 2L,
                            Content = "Отлично!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 46, 3, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 19L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 21L,
                            ChatId = 2L,
                            Content = "Что делаешь?",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 46, 4, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 20L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 22L,
                            ChatId = 2L,
                            Content = "Планирую поход в кино.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 46, 5, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 21L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 23L,
                            ChatId = 2L,
                            Content = "Какой фильм собираешься смотреть?",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 46, 6, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 22L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 24L,
                            ChatId = 2L,
                            Content = "Думаю посмотреть новый боевик.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 46, 7, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 23L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 25L,
                            ChatId = 2L,
                            Content = "Звучит интересно. Какие еще планы на выходные?",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 46, 8, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 24L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 26L,
                            ChatId = 2L,
                            Content = "Надеюсь провести время с семьей и отдохнуть.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 46, 9, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 25L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 27L,
                            ChatId = 2L,
                            Content = "Отличные планы! Удачи вам!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 46, 10, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 26L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 28L,
                            ChatId = 2L,
                            Content = "Спасибо! Буду стараться!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 46, 11, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 27L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 29L,
                            ChatId = 2L,
                            Content = "Как прошел поход в кино?",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 46, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 28L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 30L,
                            ChatId = 2L,
                            Content = "Было здорово! Фильм понравился.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 46, 13, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 29L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 31L,
                            ChatId = 2L,
                            Content = "Рад, что вам понравилось!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 46, 14, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 30L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 32L,
                            ChatId = 2L,
                            Content = "Спасибо за рекомендацию фильма.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 46, 15, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 31L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 33L,
                            ChatId = 2L,
                            Content = "Привет! Как дела?",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 8, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 32L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 34L,
                            ChatId = 2L,
                            Content = "Привет! У меня все хорошо. Как твои дела?",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 9, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 33L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 35L,
                            ChatId = 2L,
                            Content = "У меня тоже все отлично. Планируешь что-нибудь интересное на выходные?",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 10, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 34L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 36L,
                            ChatId = 2L,
                            Content = "Да, собираюсь с друзьями в парк на пикник. Будет весело!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 11, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 35L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 37L,
                            ChatId = 2L,
                            Content = "Отличная идея! Хорошо проведите время.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 12, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 36L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 38L,
                            ChatId = 2L,
                            Content = "Спасибо! Будем стараться!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 13, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 37L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 39L,
                            ChatId = 2L,
                            Content = "Какой фильм смотрели на прошлой неделе?",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 14, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 38L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 40L,
                            ChatId = 2L,
                            Content = "Мы посмотрели комедию 'Август. Восьмого'. Очень смешной фильм!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 15, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 39L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 41L,
                            ChatId = 2L,
                            Content = "Я слышал о нем! Действительно, забавная комедия.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 16, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 40L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 42L,
                            ChatId = 2L,
                            Content = "Очень рекомендую посмотреть, если у тебя будет свободное время.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 17, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 41L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 43L,
                            ChatId = 2L,
                            Content = "Спасибо за рекомендацию! Обязательно добавлю в свой список фильмов.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 18, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 42L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 44L,
                            ChatId = 2L,
                            Content = "Нет проблем! Уверен, тебе понравится.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 19, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 43L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 45L,
                            ChatId = 2L,
                            Content = "Что-нибудь интересное произошло у тебя на этой неделе?",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 20, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 44L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 46L,
                            ChatId = 2L,
                            Content = "Ничего особенного, но я получил повышение на работе! Я очень рад!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 21, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 45L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 47L,
                            ChatId = 2L,
                            Content = "Поздравляю! Ты действительно заслужил это повышение.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 22, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 46L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 48L,
                            ChatId = 2L,
                            Content = "Спасибо! Я очень старался и рад, что моя работа оценена.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 23, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 47L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 49L,
                            ChatId = 2L,
                            Content = "Теперь у тебя будет еще больше возможностей и достижений!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 24, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 48L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 50L,
                            ChatId = 2L,
                            Content = "Да, я очень мотивирован и готов взяться за новые проекты.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 25, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 49L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 51L,
                            ChatId = 2L,
                            Content = "Удачи тебе во всем! Ты сможешь добиться большого!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 26, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 50L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 52L,
                            ChatId = 2L,
                            Content = "Спасибо за поддержку! Я ценю это.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 27, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 51L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 53L,
                            ChatId = 2L,
                            Content = "Не за что! Всегда готов помочь и поддержать.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 28, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 52L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 54L,
                            ChatId = 2L,
                            Content = "Спасибо, друг! Ты лучший!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 29, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 53L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 55L,
                            ChatId = 2L,
                            Content = "И ты тоже, брат! Любые проблемы - обращайся!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 30, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 54L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 56L,
                            ChatId = 2L,
                            Content = "Конечно, буду иметь в виду! Спасибо за поддержку и дружбу!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 31, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 55L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 57L,
                            ChatId = 2L,
                            Content = "Взаимно, братан! Дружба навсегда!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 32, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 56L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 58L,
                            ChatId = 2L,
                            Content = "Да, навсегда! Будем держаться вместе!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 33, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 57L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 59L,
                            ChatId = 2L,
                            Content = "Так точно! Ни шагу назад!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 34, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 58L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 60L,
                            ChatId = 2L,
                            Content = "Вперед, к новым приключениям!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 20, 23, 47, 35, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 59L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 61L,
                            ChatId = 1L,
                            Content = "Привет! Как твои дела?",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 10, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 62L,
                            ChatId = 1L,
                            Content = "Привет! Всё отлично, спасибо! Как у тебя?",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 10, 16, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 61L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 63L,
                            ChatId = 1L,
                            Content = "У меня тоже всё хорошо. Планируешь что-нибудь интересное на выходные?",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 10, 17, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 62L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 64L,
                            ChatId = 1L,
                            Content = "Да, у меня есть небольшие планы. Хочу сходить в парк и поиграть в футбол.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 10, 18, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 63L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 65L,
                            ChatId = 1L,
                            Content = "Отличная идея! Погода должна быть хорошей. Удачи в игре!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 10, 19, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 63L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 66L,
                            ChatId = 1L,
                            Content = "Спасибо! Буду стараться показать хороший результат.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 10, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 65L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 67L,
                            ChatId = 1L,
                            Content = "У тебя есть какие-нибудь планы на вечер?",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 66L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 68L,
                            ChatId = 1L,
                            Content = "На вечер у меня нет особых планов. Возможно, просто отдохну дома и посмотрю фильм.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 31, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 67L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 69L,
                            ChatId = 1L,
                            Content = "Это звучит как хороший вариант. Можешь порекомендовать какой-нибудь фильм?",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 32, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 68L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 70L,
                            ChatId = 1L,
                            Content = "Конечно! Я недавно посмотрел фильм 'Интерстеллар'. Он очень увлекательный и захватывающий.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 33, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 69L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 71L,
                            ChatId = 1L,
                            Content = "Спасибо за рекомендацию! Обязательно посмотрю.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 34, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 70L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 72L,
                            ChatId = 1L,
                            Content = "Пожалуйста! Уверен, тебе понравится. Наслаждайся просмотром!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 35, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 71L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 73L,
                            ChatId = 1L,
                            Content = "Спасибо! Ты всегда помогаешь выбрать хорошее развлечение.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 36, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 72L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 74L,
                            ChatId = 1L,
                            Content = "Рад, что моя помощь пригождается! Если у тебя есть еще вопросы или нужна помощь, обращайся.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 37, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 73L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 75L,
                            ChatId = 1L,
                            Content = "Безусловно! Я всегда знаю, кому обратиться, когда нужна помощь или совет.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 38, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 74L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 76L,
                            ChatId = 1L,
                            Content = "Спасибо за доверие! Я всегда готов поддержать друзей.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 39, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 75L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 77L,
                            ChatId = 1L,
                            Content = "Ты лучший друг! Ценю нашу дружбу.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 40, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 76L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 78L,
                            ChatId = 1L,
                            Content = "Спасибо! Я также очень ценю нашу дружбу. Мы всегда поддержим друг друга.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 41, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 77L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 79L,
                            ChatId = 1L,
                            Content = "Так точно! Дружба навсегда!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 42, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 78L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 80L,
                            ChatId = 1L,
                            Content = "Ни шагу назад! Вместе мы сила!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 43, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 79L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 81L,
                            ChatId = 1L,
                            Content = "Точно! Ничто не сможет нас остановить!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 44, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 80L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 82L,
                            ChatId = 1L,
                            Content = "Вперед, к новым победам и успехам!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 81L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 83L,
                            ChatId = 1L,
                            Content = "Согласен! Мы не останавливаемся на достигнутом, а стремимся к большему!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 82L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 84L,
                            ChatId = 1L,
                            Content = "Точно! Вместе мы неуязвимы!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 46, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 83L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 85L,
                            ChatId = 1L,
                            Content = "Да, мы команда, сплоченная и непобедимая!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 47, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 84L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 86L,
                            ChatId = 1L,
                            Content = "Всегда готов поддержать тебя в любых начинаниях!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 48, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 85L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 87L,
                            ChatId = 1L,
                            Content = "Спасибо, друг! Твоя поддержка очень важна для меня.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 49, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 86L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 88L,
                            ChatId = 1L,
                            Content = "Всегда рад помочь! Мы вместе сила!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 21, 18, 50, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 87L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 89L,
                            ChatId = 1L,
                            Content = "Кстати, слышал о новой выставке искусства? Может быть, пойдем вместе?",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 22, 9, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 90L,
                            ChatId = 1L,
                            Content = "О, это звучит интересно! Когда и где проходит выставка?",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 22, 9, 31, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 89L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 91L,
                            ChatId = 1L,
                            Content = "Выставка проходит в местной галерее с 25 декабря по 10 января. Можем сходить в выходные.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 22, 9, 32, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 90L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 92L,
                            ChatId = 1L,
                            Content = "Отлично! Я с удовольствием присоединюсь. Выставки искусства всегда вдохновляют меня.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 22, 9, 33, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 91L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 93L,
                            ChatId = 1L,
                            Content = "Прекрасно! Уверен, мы сможем насладиться множеством талантливых работ.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 22, 9, 34, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 92L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 94L,
                            ChatId = 1L,
                            Content = "Точно! Искусство способно пробудить в нас самые глубокие эмоции и мысли.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 22, 9, 35, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 93L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 95L,
                            ChatId = 1L,
                            Content = "Не терпится увидеть выставку! Будет замечательное время вместе.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 22, 9, 36, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 94L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 96L,
                            ChatId = 1L,
                            Content = "Согласен, это будет отличная возможность провести время вместе и обсудить впечатления.",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 22, 9, 37, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 95L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 97L,
                            ChatId = 1L,
                            Content = "Точно! Не могу дождаться выходных. Давай встретимся возле галереи в субботу в 12:00?",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 22, 9, 38, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 96L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 98L,
                            ChatId = 1L,
                            Content = "Отлично, договорились! Увидимся в субботу возле галереи в 12:00. Буду ждать с нетерпением!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 22, 9, 39, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 97L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 99L,
                            ChatId = 1L,
                            Content = "Супер! Уже не могу дождаться нашей встречи. До субботы!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 22, 9, 40, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 98L,
                            MessageTypeId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 100L,
                            ChatId = 1L,
                            Content = "До встречи! Приятного дня и до скорого!",
                            DateCreate = new DateTimeOffset(new DateTime(2022, 12, 22, 9, 41, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            DeletedByAll = false,
                            ForwardedMessageId = 99L,
                            MessageTypeId = 1L,
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("PowerMessenger.Domain.Entities.MessageStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<long?>("LastMessageReadId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_message_read_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_message_statuses");

                    b.HasIndex("ChatId")
                        .HasDatabaseName("ix_message_statuses_chat_id");

                    b.HasIndex("LastMessageReadId")
                        .HasDatabaseName("ix_message_statuses_last_message_read_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_message_statuses_user_id");

                    b.ToTable("message_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ChatId = 1L,
                            LastMessageReadId = 12L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            ChatId = 1L,
                            LastMessageReadId = 11L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            ChatId = 2L,
                            LastMessageReadId = 16L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            ChatId = 2L,
                            LastMessageReadId = 14L,
                            UserId = 2L
                        });
                });

            modelBuilder.Entity("PowerMessenger.Domain.Entities.MessageType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_message_types");

                    b.ToTable("message_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Type = "Text"
                        },
                        new
                        {
                            Id = 2L,
                            Type = "Image"
                        });
                });

            modelBuilder.Entity("PowerMessenger.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<DateTimeOffset?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Theme")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("theme");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasAlternateKey("UserId")
                        .HasName("ak_users_user_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_user_id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            UserId = 1L,
                            UserName = "PowerBlaze"
                        },
                        new
                        {
                            Id = 2L,
                            UserId = 2L,
                            UserName = "TowerBlaze"
                        });
                });

            modelBuilder.Entity("PowerMessenger.Domain.Entities.Chat", b =>
                {
                    b.HasOne("PowerMessenger.Domain.Entities.ChatType", "ChatType")
                        .WithMany("Chats")
                        .HasForeignKey("ChatTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chats_chat_types_chat_type_id");

                    b.Navigation("ChatType");
                });

            modelBuilder.Entity("PowerMessenger.Domain.Entities.ChatParticipant", b =>
                {
                    b.HasOne("PowerMessenger.Domain.Entities.Chat", "Chat")
                        .WithMany("ChatParticipants")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_participants_chats_chat_id");

                    b.HasOne("PowerMessenger.Domain.Entities.User", "User")
                        .WithMany("ChatParticipants")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_participants_users_user_id");

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PowerMessenger.Domain.Entities.Message", b =>
                {
                    b.HasOne("PowerMessenger.Domain.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_chats_chat_id");

                    b.HasOne("PowerMessenger.Domain.Entities.User", "DeletedByUser")
                        .WithMany("DeletedMessages")
                        .HasForeignKey("DeletedByUserId")
                        .HasPrincipalKey("UserId")
                        .HasConstraintName("fk_messages_users_deleted_by_user_id");

                    b.HasOne("PowerMessenger.Domain.Entities.Message", "ForwardMessage")
                        .WithMany()
                        .HasForeignKey("ForwardedMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_messages_messages_forward_message_id");

                    b.HasOne("PowerMessenger.Domain.Entities.MessageType", "MessageType")
                        .WithMany("Messages")
                        .HasForeignKey("MessageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_message_types_message_type_id");

                    b.HasOne("PowerMessenger.Domain.Entities.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_user_id");

                    b.Navigation("Chat");

                    b.Navigation("DeletedByUser");

                    b.Navigation("ForwardMessage");

                    b.Navigation("MessageType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PowerMessenger.Domain.Entities.MessageStatus", b =>
                {
                    b.HasOne("PowerMessenger.Domain.Entities.Chat", "Chat")
                        .WithMany("MessageStatuses")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_statuses_chats_chat_id");

                    b.HasOne("PowerMessenger.Domain.Entities.Message", "Message")
                        .WithMany("MessageStatuses")
                        .HasForeignKey("LastMessageReadId")
                        .HasConstraintName("fk_message_statuses_messages_message_id");

                    b.HasOne("PowerMessenger.Domain.Entities.User", "User")
                        .WithMany("MessageStatuses")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_statuses_users_user_id");

                    b.Navigation("Chat");

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PowerMessenger.Domain.Entities.Chat", b =>
                {
                    b.Navigation("ChatParticipants");

                    b.Navigation("MessageStatuses");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PowerMessenger.Domain.Entities.ChatType", b =>
                {
                    b.Navigation("Chats");
                });

            modelBuilder.Entity("PowerMessenger.Domain.Entities.Message", b =>
                {
                    b.Navigation("MessageStatuses");
                });

            modelBuilder.Entity("PowerMessenger.Domain.Entities.MessageType", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PowerMessenger.Domain.Entities.User", b =>
                {
                    b.Navigation("ChatParticipants");

                    b.Navigation("DeletedMessages");

                    b.Navigation("MessageStatuses");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
